### ISSUE TITLE
Support for SHA256 in authenticode signatures

### ISSUE THREAD

**Issue by jdval** [ralphje/signify#1]
Hi there,

I backported this library to work in python 2 here: https://github.com/jdval/signify (we're planning to migrate to python 3 soon though!)

I just made a few changes (along with a test file) to support sha256 in authenticode signatures: https://github.com/jdval/signify/pull/1/files - I don't think I can create a new fork of your original py3 repo to make those changes though

**Comment by ralphje** [comment]
I have merged your changes to the codebase. Thank you so much for your time.
