### ISSUE TITLE
Support for SHA-384 algorithm

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#10]
I just came across an executable signed by LumiraDx Care Solutions UK Ltd (added the sample here), which crashes `signify`  with the following error:

`SignerInfo.digestAlgorithm must be one of ['md5', 'sha1', 'sha256'], not 2.16.840.1.101.3.4.2.2`

The above OID represents the SHA-384 algorithm. Two out of the three certificates in the chain are SHA-384 (the end-certificate is SHA-256), as well as the countersignature. Any plans on adding support to this algorithm?

[sha384_sample.zip](https://github.com/ralphje/signify/files/4784587/sha384_sample.zip)

**Comment by ralphje** [comment]
I have added the algorithms to the code, though I couldn't verify the provided sample fully as the root CA apparently isn't trusted for the countersignature. Can you verify that the fix works?

**Comment by MrCrumbs** [comment]
Thanks! It's weird because Windows verifies the countersignature with issuer `Sectigo RSA Time Stamping CA` while the validation fails because:

`Chain verification from CN=Sectigo RSA Time Stamping Signer #1, O=Sectigo Limited, L=Salford, ST=Greater Manchester, C=GB(serial:81218991475802577581165217999722004744) failed: Unable to build a validation path for the certificate "Common Name: Sectigo RSA Time Stamping Signer #1, Organization: Sectigo Limited, Locality: Salford, State/Province: Greater Manchester, Country: GB" - no issuer matching "Common Name: USERTrust RSA Certification Authority, Organization: The USERTRUST Network, Locality: Jersey City, State/Province: New Jersey, Country: US" was found

`This is weird since the issuer name in the error isn't the one displayed by Windows.

Anyway, unfortunately I do not have another such sample right now...

**Comment by MrCrumbs** [comment]
Sorry I closed by mistake. Do you think the comment above is worth more investigation?

**Comment by ralphje** [comment]
I have added more CA's today and now it completely verifies.
