### ISSUE TITLE
Recurring error checking the countersigner hash

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#14]
I have many samples where Windows validates the counter-signature, but `signify` crashes with:

`AuthenticodeVerificationError('The expected hash of the encryptedDigest does not match countersigner's SignerInfo')`

I'm not sure yet what's wrong in this check, but it doesn't allow to validate many valid signatures (valid at least according to Windows). Can you take a look and see what we're missing here? I uploaded 2 legit samples where this happens (Windows validates, `signify` doesn't). Thanks!

[samples.zip](https://github.com/ralphje/signify/files/4946617/samples.zip)

**Comment by ralphje** [comment]
Sorry I didn't get back to you sooner, but the error originated because there was the assumption that two algorithms in RFC3161 signed data must always be the same, though they mustn't.

**Comment by MrCrumbs** [comment]
Great, thanks for the update! Is a new release planned?

**Comment by ralphje** [comment]
Yes I will create a patch release soon. Can you confirm that you don't run into issues with the latest commit?

**Comment by MrCrumbs** [comment]
Yes, I have tested it out a bit and can confirm it is working perfectly. Thanks! A release would be awesome.
