### ISSUE TITLE
Support more certificate revisions?

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#17]
I have a McAfee installer sample which Windows verifies correctly, while with Signify I get:

`SignedPEParseError('Unknown certificate revision 3d6e',)`

Any plans to support other revisions as well?
[mcafee_sample.zip](https://github.com/ralphje/signify/files/5360728/mcafee_sample.zip)

**Comment by ralphje** [comment]
Seems that this binary has some random XML in its certificate table, resulting in this error:

![Screenshot 2024-06-08 190809](https://github.com/ralphje/signify/assets/1107949/efd661de-a62a-474a-bc6c-e0e040366045)

I have at least fixed a bug with trying to read too many bytes resulting in a `MemoryError`, but I'm not really sure how to proceed. You could simply read the first `SignerInfo` and that should work fine.
