### ISSUE TITLE
Support more `SignerInfo` versions?

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#18]
I have a sample of a Spotify installer which Windows verifies correctly, while Signify returns:

`SignerInfoParseError('SignerInfo.version must be 1, not 0',)`

Any plans on supporting other `SignerInfo` versions as well?
[spotify_sample.zip](https://github.com/ralphje/signify/files/5360729/spotify_sample.zip)

**Comment by ralphje** [comment]
Fixed per https://github.com/ralphje/signify/commit/ddd32e313112dafa440d8047836feee2eaa0e224
