### ISSUE TITLE
Cert Table parsing error

### ISSUE THREAD

**Issue by Stas25519** [ralphje/signify#19]
I've had issues parsing PEs with more than one signature in the table, and I believe it is caused by the following line in `_parse_cert_table()`. If length is already aligned,`length + (8 - (length % 8))` -> `length + 8`. From what I can tell by reading the docs https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#the-attribute-certificate-table-image-only, length should not by incremented by 8 if it is already aligned ("round up to the nearest 8-byte multiple").

https://github.com/ralphje/signify/blob/d0d0e018bceb4802f4df0c7ecccb80d5e24a0bc1/signify/signed_pe.py#L194

I tried to locally add a check for the special case where `length % 8 == 0`, and it seemed to solve the issue.

**Comment by ralphje** [comment]
I would love to add tests for this, perhaps there are some suitable samples already, but this should fix the issue.
