### ISSUE TITLE
Exception raised if script is compiled by pyinstaller

### ISSUE THREAD

**Issue by YJesus** [ralphje/signify#23]
scenario a: Python39 as interpreter:

Script: 

from signify import signed_pe
from signify.exceptions import SignedPEParseError
import pefile

with open("C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", "rb") as petotest:
	try:
		pefile = signed_pe.SignedPEFile(petotest)
		pefile.verify()
						
	except Exception as ex:
						
		print (ex)

Result --> OK

scenario b: compiled version of the script

If I do
pyinstaller --onefile script.py

and run the same code:

exception raised:

An error occurred while validating the countersignature.

**Comment by YJesus** [comment]
If I call verify with 

pefile.verify(allow_countersignature_errors=True)

I got:

Chain verification from CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, ST=Washington, C=US (serial:1137338007632646875454199647675853639488897506, sha1:c774204049d25d30af9ac2f116b3c1fb88ee00a4) failed: Unable to build a validation path for the certificate "Common Name: Microsoft Corporation, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US" - no issuer matching "Common Name: Microsoft Root Certificate Authority 2011, Organization: Microsoft Corporation, Locality: Redmond, State/Province: Washington, Country: US" was found

So I suspect the problem is in the download of authroot.stl

If I run:
import pathlib
import struct



AUTHROOTSTL_URL = "http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authroot.stl"
AUTHROOTSTL_PATH = pathlib.Path(__file__).resolve().parent.parent / "certs" / "authroot.stl"


print (AUTHROOTSTL_PATH)

I got different paths between interpreted VS compiled 

Compiled: 

certs\authroot.stl

**Comment by ralphje** [comment]
It appears that the location for the certs directory can not be found, which means that the bundled certificates are not loaded. I've done some research but can't find how this is supposed to work.

**Comment by jgstew** [comment]
PyInstaller may require a MANIFEST file in the project to tell it to include extra items, or an option to include the extra data.

**Comment by ralphje** [comment]
I have separated out the certificates to a separate repository. This means that the pyinstaller hook is now also gone.

Could you perhaps check it is also required with this new package? I'd be happy to add it back in.

**Comment by alekpc** [comment]
Hi,
I have the same problem. When script gets compiled into single file executable by pyinstaller during runtime I get an error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3r/vv9n8_yn5170q7wm11d748vm0000gn/T/_MEIV7GVmv/mscerts/authroot.stl'
```
Additing authroot.stl to pyinstaller spec script as data apparently does not work, at least on Mac OS X. 

I'm using:
* Mac OS X 13.4.1 (ARM64)
* Python 3.10.12
* signify 0.5.2
* pyinstaller 5.13.0
