### ISSUE TITLE
SignerInfoVerificationError with valid signature

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#25]
Hey, seems that the following sample's signature is fine according to Windows, however with `signify` I get `SignatureError: Signature is invalid`. 

Any ideas?

(adding download link because of GitHub bug)
https://drive.google.com/file/d/1NKqGtOAdx_14Hb1dMDsIxCHDOtY0MWfE/view?usp=sharing

**Comment by ralphje** [comment]
This took a while to figure out. After digging through pyasn1 I found a single `sort()` statement that messed everything up. Unfortunately, it is not really feasible to fetch the original DER encoded value from the pyasn1 structure, so this should do.

**Comment by MrCrumbs** [comment]
Thanks. It would really help us if you could publish a new release with your latest code (It would be exactly 1 year from last release ;)). Would that be possible?

**Comment by ralphje** [comment]
I'm looking to do so soon, though I have been able to do some research into #12 which I would really like to implement first

**Comment by MrCrumbs** [comment]
I see. Ok thanks for your reply, I'll wait for the release whenever you can make it. Thanks so much for your great work!

**Comment by ralphje** [comment]
@MrCrumbs Given that you are using it quite often, could you perhaps test the newest version before I push it to v0.4? I believe everything is correct and the tests are green, though a double-check would be nice :)

**Comment by ralphje** [comment]
I appreciate your help. I have just released 0.4.0.

**Comment by MrCrumbs** [comment]
Thanks so much!
