### ISSUE TITLE
How to do certificate pinning?

### ISSUE THREAD

**Issue by nihil-admirari** [ralphje/signify#28]
How to make sure that `SignedPEFile.verify()` validates against the expected certificate, not just some random certificate whose chain happens to lead to trust store?

**Comment by ralphje** [comment]
If you want to check the exact certificate that is used to sign with, you can simply ignore the certificates included in the SignedData structure, and simplify to using a VerificationContext with only your ``cs`` store. 

If you want to check it has some chain back to a specific CA, yes, you need to do it something like this, although it would fail in the case of multiple SignedDatas present in your PE file.
