### ISSUE TITLE
Add to README.rst or Docs "Examples" section.

### ISSUE THREAD

**Issue by jgstew** [ralphje/signify#32]
This took me longer than I'd like to admit to figure out: https://github.com/jgstew/tools/blob/master/Python/get_pefile_signify_time.py

Would be nice to have an "Examples" section.

**Comment by ralphje** [comment]
The documentation for Authenticode did already show a very basic example. I have expanded this to include the signing time as well. I have also moved the shell script to an appropriate location.

If you feel that more documentation would be helpful, please re-open this ticket.
