### ISSUE TITLE
Question - planned stable release?

### ISSUE THREAD

**Issue by arthurvai** [ralphje/signify#35]
Hi,
Latest 0.4 release was two years ago and it seems like there are a lot of additional fixes since then.
Is there a new release planned? If not, is there a specific commit you consider stable?

Also, thanks for developing and maintaining this library !

**Comment by ralphje** [comment]
I agree that a new release is in order. Never realized that it has already been 1.5 years. I plan to split off the certificate bundles into a separate repository, so they can update independently.
