### ISSUE TITLE
Error： oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

### ISSUE THREAD

**Issue by gaohang** [ralphje/signify#41]
Why? How to fix it?

Code as below：
from signify.authenticode import SignedPEFile

Error msg:
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

**Comment by ralphje** [comment]
This seems to be an issue with dependency oscrypto. Please see https://github.com/wbond/oscrypto#dependencies for more details
