### ISSUE TITLE
Incorrect handling of  SpcPeImageData in 0.7

### ISSUE THREAD

**Issue by mvanderlee** [ralphje/signify#46]
Starting with 0.7, MSI's can no longer be verified.

While I don't understand the mechanisms in place, it is due to the newly added `SpcPeImageData` handling in 0.7. At a glance, it appears that we're comparing to a string, when we should be comparing to a OID?

Error occurs here:
https://github.com/ralphje/signify/blob/master/signify/authenticode/structures.py#L362

The content type in my MSI is `1.3.6.1.4.1.311.2.1.30`, not `microsoft_spc_pe_image_data`

I've found a reference to the content type here: 
```
/* Microsoft OID Authenticode */
#define SPC_INDIRECT_DATA_OBJID      "1.3.6.1.4.1.311.2.1.4"
#define SPC_STATEMENT_TYPE_OBJID     "1.3.6.1.4.1.311.2.1.11"
#define SPC_SP_OPUS_INFO_OBJID       "1.3.6.1.4.1.311.2.1.12"
#define SPC_PE_IMAGE_DATA_OBJID      "1.3.6.1.4.1.311.2.1.15"
#define SPC_CAB_DATA_OBJID           "1.3.6.1.4.1.311.2.1.25"
#define SPC_SIPINFO_OBJID            "1.3.6.1.4.1.311.2.1.30"
```

Source: https://github.com/mtrojnar/osslsigncode/blob/master/osslsigncode.h#L181

Based on this, and the Word document I found in comments: https://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/authenticode_pe.docx
I think you mean to check for 
```python
if self.content_type != "1.3.6.1.4.1.311.2.1.15":
```

However, this would still break my MSI usecase. Why is the `SpcPeImageData` required by signify?

MSI reference: I followed this [suggestion](https://github.com/ralphje/signify/issues/24#issuecomment-1148320566), which works great <0.7

**Comment by mvanderlee** [comment]
Additional OID information: 
* https://www.betaarchive.com/wiki/index.php?title=Microsoft_KB_Archive/287547
* http://oid-info.com/get/1.3.6.1.4.1.311.2.1.30

**Comment by ralphje** [comment]
Thanks for your report. This commit should fix it, please let me know if it doesn't work. Please note that since 0.7 we translate a lot of OIDs to strings , so that's why you see the comparison against a string. The matter of the fact is that we just hadn't seen those OIDs yet.

A similar issue may exist with 1.3.6.1.4.1.311.2.1.25 (SPC_CAB_DATA_OBJID) and 1.3.6.1.4.1.311.2.1.28 (SPC_LINK_OBJID), but I haven't been able to find samples with these OIDs.

**Comment by mvanderlee** [comment]
Fantastic, I hadn't seen the mapping yet. 
I have just tested by installing that commit, and it works like a charm. Thank you for the incredibly quick turnaround! Dankjewel 


Tested via:
```bash
pip install 'git+https://github.com/ralphje/signify.git@c98685df378ee5f8390ce57a7ff0c4368db2dbb6'
```
