### ISSUE TITLE
Question - CRL verification support

### ISSUE THREAD

**Issue by MrCrumbs** [ralphje/signify#7]
This is more of a question than an issue:

Does Signify support verifying that a certificate SN does not appear in its CRL? For example, I have a sample where Windows alerts that the certificate has been revoked by its issuer, but Signify verifies the signature and doesn't know that it appears in the CRL, so it thinks everything is OK.

Is there CRL support that I'm missing? If not, what is the most correct way to go about this? For each certificate, download its CRL, and check if the certificate's SN appears in the list? Is there a better way to check this?

PS - When is your next planned release? I need to decide if we should build the current code ourselves, or wait for your release (which is better of course. Thanks!)

**Comment by ralphje** [comment]
You are entirely correct that CRLs are not checked. I should also add that a CTL verification is also lacking at this time. I will look into this, and then publish a new release.

If you have an example file, can you send it to me?

**Comment by MrCrumbs** [comment]
Sure. Please notice this file is malware (I am a malware researcher), and that's why it is using a revoked certificate. Please do not run it on your system (but its signature data can be analyzed anyway). In this sample, the `James LTH d.o.o.` certificate's serial number appears in the embedded CRL. So even though Signify verifies it, Windows alerts that:

![image](https://user-images.githubusercontent.com/5943547/80361103-0b515c80-8889-11ea-8800-95f91c66ea8e.png)

Malicious Sample:
[malicious.zip](https://github.com/ralphje/signify/files/4538983/malicious.zip)

**Comment by ralphje** [comment]
I have created a 0.2.0 release. An example on how to force CRL checks can be seen here: https://github.com/ralphje/signify/blob/master/tests/test_context.py#L44-L46

**Comment by MrCrumbs** [comment]
Thanks so much for the amazing and swift work!
